init: create custom components
AnastasC/webix-custom pull request #1
Opened 2022-04-13 18:58 UTC by AnastasC

2022-04-14 07:26 UTC, olimed commented on sources/protos/protoMybutton.js
> +        let { state, states } = config;
если в `config` не будет свойств `state` and `states`, то дальше в коде могут возникать ошибки, чтобы этого избежать иногда стоит использовать проверки.
+ это предоставляет возможность использовать дефолтные значения в компоненте.

2022-04-14 07:26 UTC, olimed commented on sources/views/toolbal.js
> +            id: "mybutton",
старайся давать боее осознанные имена вьюшкам и элементам

2022-04-14 07:26 UTC, olimed commented on sources/protos/protoMybutton.js
> +        const styles = ["sort_off", "sort_asc", "sort_desc"];
так как стили используются только для данного компонента, то лучше с помощью селектора указывать, что они для этого компонента, например:
`mybutton__state--sort-off`

2022-04-14 07:26 UTC, olimed commented on sources/protos/protoFormControl.js
> +            onCancel: () => console.log('cancel'),
очень классная функция😀) но лучше в проекте такие не создавать

2022-04-14 07:26 UTC, olimed commented on sources/protos/protoFormControl.js
> +                console.log($$(this.id).getValues());
смотри комментарий выше😀

2022-04-14 07:26 UTC, olimed commented on sources/protos/protoFormControl.js
> +                                    this.config.onCancel();
форма должна очищаться от значений если в конфиге нет события onCancel

2022-04-14 07:26 UTC, olimed commented on sources/protos/protoFormControl.js
> +                                    this.config.onSave();
если нет в конфиге этого события, то выводи сообщение (webix.message) со значениями формы

2022-04-14 07:26 UTC, olimed commented on sources/protos/protoFormControl.js
> +            return values;
а зачем переопределять метод у формы, если в нем ты вызываешь этот же метод и возвращаешь его результат?

2022-04-14 14:48 UTC, olimed commented on sources/protos/protoFormControl.js
> +                }
можно использовать `Object.values(obj).jon('; ');`

2022-04-14 18:08 UTC, HelgaListopad requested changes

2022-04-14 18:08 UTC, HelgaListopad commented on sources/protos/protoFormControl.js
> +            this.define("elements", formElements);
`define` для элементов UI лучше не использовать. 
Этот метод нужен в первую очередь для переопределения собственных свойств компонента, а тут речь идёт о создании вложенных вьюшек. 

После инита он, кстати, так не сработает.) 
На этом этапе получилось скорее случайно - так как из config ещё не начали строиться child views. 

Прямо тут есть смысл написать `config.elements = formElements`

2022-04-14 18:08 UTC, HelgaListopad commented on sources/protos/protoFormControl.js
> +            this.define("elements", formElements);
На всякий случай (не касается твоего кода) напишу и о том, что то же самое не надо делать в `defaults` - там тоже должны задаваться только свойства, а не вложенные компоненты (и не `data`/`url`)

2022-04-14 18:08 UTC, HelgaListopad commented on sources/protos/protoSortButton.js
> +        if( !state && !states ) return;
Было бы неплохо по умолчанию присваивать первый (нулевой) state, если они заданы
Иначе у тебя на ините получается четвёртое, "никакое" состояние компонента.

Начальное состояние не должно триггерить onStateChange.
Это необязательно, но если тебе покажется уместным сортировать лист по исходному значению, можешь в `ready` листа получить state кнопки и вызвать сортировку.

2022-04-15 15:24 UTC, HelgaListopad approved these changes

2022-04-15 15:30 UTC, olimed commented on sources/protos/protoSortButton.js
> +            this.define({
Оля писала, что `define` не стоит использовать в UI компонентах

2022-04-15 18:46 UTC, merged